name = "eFEM"
uuid = "2c183d4b-6912-41f6-9bbe-3a8bfc9d38a6"
authors = ["Patrick Eastham"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
